# Generated by Django 4.2.3 on 2023-07-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatesDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=50)),
                ('longitude', models.FloatField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatesHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=50)),
                ('longitude', models.FloatField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatesMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=50)),
                ('longitude', models.FloatField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('precipitate', models.CharField(max_length=20)),
                ('coordinatesMinutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinatesminutes')),
            ],
        ),
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('windspeed', models.FloatField()),
                ('weather', models.CharField(max_length=30)),
                ('coordinatesHourly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinateshourly')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('maxtemperature', models.IntegerField()),
                ('mintemperature', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('windspeed', models.FloatField()),
                ('weather', models.CharField(max_length=30)),
                ('coordinatesDays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coordinatesdays')),
            ],
        ),
    ]
